### ISSUE TITLE
Queries with spaces in don't work

### ISSUE THREAD

**Issue by charlesroper** [jdrever/ShropBotSoc#101]
Search for _Orobanche_ returns 4 rows

Search for _Orobanche hederae_ returns nothing

Search for _Ivy Broomrape_ (common name) returns nothing

**Comment by jdrever** [comment]
Yes, I thought I had this working, but now can’t get any combination of query to yield any results.  Have asked Sophia for some guidance.

From: Charles Roper ***@***.***>
Sent: 18 April 2021 03:58
To: jdrever/ShropBotSoc ***@***.***>
Cc: James Drever ***@***.***>; Assign ***@***.***>
Subject: [jdrever/ShropBotSoc] Queries with spaces in don't work (#101)


Search for Orobanche returns 4 rows

Search for Orobanche hederae returns nothing

Search for Ivy Broomrape (common name) returns nothing

**Comment by jdrever** [comment]
With the quote stripping in NbnRecords sorted, this is also sorted.
