### ISSUE TITLE
Records counts aren't consistent

### ISSUE THREAD

**Issue by charlesroper** [jdrever/ShropBotSoc#102]
To reproduce:

1. Search for _Orobanche_ and you should see 1 in the Records column for Orobanche hederae
2. Click on Orobanche hederae
3. 3020 records are apparently returned, filling the whole map with dots - there should be only 1 dot and 1 site.

Even if there is supposed to be 3020 records in the results, only those on the current page should be shown. It looks like all records from all pages are being show at the moment.

![image](https://user-images.githubusercontent.com/176/115132774-07b76800-9ffb-11eb-8347-40035f5e8191.png)

**Comment by jdrever** [comment]
Which branch are you on, Charles?

This is my local develop branch, works ok for me.

***@***.***D7352D.9948E250]

From: Charles Roper ***@***.***>
Sent: 18 April 2021 04:05
To: jdrever/ShropBotSoc ***@***.***>
Cc: James Drever ***@***.***>; Assign ***@***.***>
Subject: [jdrever/ShropBotSoc] Records counts aren't consistent (#102)


To reproduce:

  1.  Search for Orobanche and you should see 1 in the Records column for Orobanche hederae
  2.  Click on Orobanche hederae
  3.  3020 records are apparently returned, filling the whole map with dots - there should be only 1 dot and 1 site.

Even if there is supposed to be 3020 records in the results, only those on the current page should be shown. It looks like all records from all pages are being show at the moment.

<https://user-images.githubusercontent.com/176/115132774-07b76800-9ffb-11eb-8347-40035f5e8191.png>

**Comment by charlesroper** [comment]
This was on branch 4.2.2-map-showing...

See PR #100

I probably broke something making changes there.

**Comment by jdrever** [comment]
Looks like the difference is that double quotes aren’t surrounding the taxon_name in the API call..  Can’t quite see why that would be the case looking at differences in the code.  And the API is being so flakey at the moment, I think I need to take a break 😊

**Comment by jdrever** [comment]
Closed, after spotting that stripping quotes out in NBNRecords was causing the issue.
