### ISSUE TITLE
Bug: NBN WMS record markers disappear when zoomed in

### ISSUE THREAD

**Issue by charlesroper** [jdrever/ShropBotSoc#105]
To reproduce:

1. Search for _Hedera hibernica_ and go to page 2 (http://localhost:8089/species/Hedera%20hibernica?page=2)

2. The results returned can be inconsistent ([non-deterministic](https://en.wikipedia.org/wiki/Nondeterministic_algorithm)) but hopefully you can see one or two records in Shrewsbury

![2021-04-20_02h24_09](https://user-images.githubusercontent.com/176/115324410-bdacbe80-a181-11eb-81ae-d0e2192268e3.png)

3. With 1km grid references (e.g., SJ4912), the 1km square disappears once we zoom in past a certain point.

![2021-04-20_02h25_04](https://user-images.githubusercontent.com/176/115324639-1aa87480-a182-11eb-9a7c-fb2f9de6748d.png)

SJ4912 is the square that starts at the footbridge to the top-left and Asda down at the bottom-right. There should be a yellow square over the whole lot. Is this an API setting? Can the squares be set to stay visible? Or is this a bug (or anti-feature)?

**Comment by jdrever** [comment]
Think this is an issue with the web mapping service - conversation with Charles.  Renders a raster grid as an overlay - disappears when zoomed in too far.

**Comment by jdrever** [comment]
Fixed by @tomdrever so closing..
