### ISSUE TITLE
Bug: the Leaflet osGraticule plugin doesn't work - replace with Leaflet.MetricGrid

### ISSUE THREAD

**Issue by charlesroper** [jdrever/ShropBotSoc#106]
The osGraticule is misaligned. 

The following is more recent and used on the Geograph site, so will switch to this: https://github.com/bill-chadwick/Leaflet.MetricGrid

**Comment by jdrever** [comment]
-- The osGraticule is misaligned.
I’m just going to nod wisely & pretend I know what that means 😊

From: Charles Roper ***@***.***>
Sent: 20 April 2021 02:55
To: jdrever/ShropBotSoc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jdrever/ShropBotSoc] Bug: the Leaflet osGraticule plugin doesn't work - replace with Leaflet.MetricGrid (#106)


The osGraticule is misaligned.

The following is more recent and used on the Geograph site, so will switch to this: https://github.com/bill-chadwick/Leaflet.MetricGrid

**Comment by charlesroper** [comment]
😄

A graticule is a grid over a map.

The OS graticule is the blue grid over the top of all Ordnance Survey maps and is what we derive OS grid references from.

There's a plugin for Leaflet that draws an OS graticule over the map, which is what Joe included in his code. But it doesn't work properly - for whatever reason, the algorithm that generates the grid renders the lines (slightly) in the wrong places.

So I need to swap that old plugin out for the newer Metric Grid plugin which does the same thing and I believe is correct and is used on the http://www.geograph.org.uk/ website (which is an excellent site if you've not seen it before).

**Comment by charlesroper** [comment]
You can see in this image how the graticule doesn't line up with the NBN squares. The squares are correct.

https://user-images.githubusercontent.com/176/115324410-bdacbe80-a181-11eb-81ae-d0e2192268e3.png

**Comment by jdrever** [comment]
Fixed by @tomdrever so closing..
