### ISSUE TITLE
4.1.2 Species Search: Changing any radio button will renew the search using the changed set of parameters, without pressing return or clicking on the button.

### ISSUE THREAD

**Issue by jdrever** [jdrever/ShropBotSoc#23]
See https://github.com/jdrever/ShropBotSoc/blob/develop/docs/specification.md#412-species-search

**Comment by charlesroper** [comment]
@jdrever This one is dependent on the other issues, e.g. #12 and #22, to work properly, although I can get the intention working for now.

I'll add this to the list of things to do next.

#19 is closely related to this. When changing the radio buttons, the search will be executed as it is in #19.

**Comment by charlesroper** [comment]
On reflection, I think having the search execute automatically (and thus trigger a full page refresh) when changing radio buttons might be a usability issue, especially for people using keyboard navigation. I think we should defer this one as a backlog item to look at when the code is more mature.

Ideally we would want to handle this with an AJAX request where we swap out just the data table.

**Comment by jdrever** [comment]
I've done a super-simple implementation of this (in the spirit of trying to deliver against the spec), which we can roll back after discussion with ShropBot.  Agree we'd want to use AJAX ideally.
