### ISSUE TITLE
4.1.2 Species Search: If the search result list is long pages links should be provided.

### ISSUE THREAD

**Issue by jdrever** [jdrever/ShropBotSoc#24]
See https://github.com/jdrever/ShropBotSoc/blob/develop/docs/specification.md#412-species-search

Just needs to be confirmed.

**Comment by jdrever** [comment]
Works, but Previous/Next buttons aren't enabled/disabled appropriately.

**Comment by charlesroper** [comment]
The HTML is in place for this in view (see `species_search.php` [here](https://github.com/jdrever/ShropBotSoc/blob/develop/src/app/Views/species_search.php#L90-L98)). Needs hooking up to back-end.

**Comment by jdrever** [comment]
I'm working on this - CodeIgniter has out of the box pagination for database results, not so straightforward for API results apparently.
