### ISSUE TITLE
4.2.1 Title should be the scientific name or common name depending on which was clicked on in the previous page.

### ISSUE THREAD

**Issue by charlesroper** [jdrever/ShropBotSoc#46]
See: https://github.com/jdrever/ShropBotSoc/blob/develop/docs/specification.md#421-records-list

![image](https://github.com/jdrever/ShropBotSoc/raw/develop/docs/wireframes/Records__SingleSpeciesForCounty.png)

**Comment by jdrever** [comment]
@charlesroper This is part of Deliverable 1 not 2, Charles - unless I've misinterpreted you?

**Comment by charlesroper** [comment]
Yes, all of the 4s are part of deliverable 1. I have misassigned it - sorry to cause confusion.

**Comment by jdrever** [comment]
No worries, I’ll update 😊

**Comment by charlesroper** [comment]
I already updated it when I replied. 🙂

**Comment by jdrever** [comment]
Have sorted this one - see linked pull request.
