### ISSUE TITLE
4.2.1 The << goes back to the search for a species name using the same search parameters.

### ISSUE THREAD

**Issue by charlesroper** [jdrever/ShropBotSoc#47]
See https://github.com/jdrever/ShropBotSoc/blob/develop/docs/specification.md#421-records-list

How this is implemented will depend on the routes. We can't guarantee how someone arrives at this page (could even be a bookmark) so this back button will need to take the parameters encoded in the URL and pass them back to be decoded and injected into the search page.

![image](https://github.com/jdrever/ShropBotSoc/raw/develop/docs/wireframes/Records__SingleSpeciesForCounty.png)

**Comment by jdrever** [comment]
This is implemented.
