### ISSUE TITLE
4.2.2 Map: The map overlay comes from the NBN Web Mapping Service showing a distribution map of the species.

### ISSUE THREAD

**Issue by jdrever** [jdrever/ShropBotSoc#65]

**Comment by jdrever** [comment]
@charlesroper I am assuming we can just close this one?  Are you ok to go through the issues that relate to mapping and close any that are complete?

**Comment by jdrever** [comment]
@charlesroper just to also note: the mapping doesn't work on the ShropBotServer - https://captain-magenta.azurewebsites.net/species/Hedera%20hibernica?name=Atlantic+Ivy looks like just because the new json file hasn't got pulled over, but can you double-check before I ask Joe to amend the build process to include it?

**Comment by charlesroper** [comment]
Will do re. the mapping issues.

The error about the boundary map, will take a look. What makes you think it's problem loading the new geojson file?

**Comment by jdrever** [comment]
Because it’s not there/404ing on the testing server

**Comment by charlesroper** [comment]
Ah, the error I am seeing looks unrelated, but it's a red herring. Looks like the API is down.

![image](https://user-images.githubusercontent.com/176/114910179-79ce5800-9e15-11eb-8a5d-97bc0d870c2b.png)

**Comment by charlesroper** [comment]
Probably need an addition to the spec to check for and handle API outage. I suspect we might need it.

**Comment by jdrever** [comment]
@charlesroper presume this can now be closed, as implemented and now working on the testing server?

**Comment by charlesroper** [comment]
Yes!
