### ISSUE TITLE
NBN QUERY: How do we sort by common name for species?

### ISSUE THREAD

**Issue by jdrever** [jdrever/ShropBotSoc#93]
This is what I assumed would work:

https://records-ws.nbnatlas.org/explore/group/ALL_SPECIES?q=data_resource_uid:dr782&fq=common_name:Ivy*%20AND%20species_group:Plants+Bryophytes&facets=&sort=common_name&fsort=&dir=asc&pageSize=10&start=0

I've also tried sort=commonName and sort=commonNameSingle but they don't work either.

**Comment by charlesroper** [comment]
Don't forget you can ask questions on the forum: 

https://forums.nbn.org.uk/viewforum.php?id=46

There might well be people there who can get you a quick answer.

**Comment by jdrever** [comment]
Have emailed Sophia

**Comment by jdrever** [comment]
Sorted, using https://records-ws.nbnatlas.org//occurrences/search?q=data_resource_uid:dr782&fq=common_name:H*%20AND%20species_group:Plants+OR+Bryophytes&facets=common_name_and_lsid&sort=&fsort=index&dir=asc&flimit=10&pageSize=10&facet.offset=0 as suggested by Sophia - using either common_name_and_lsid or names_and_lsid depending on whether common or scientific name, then sorting by index.
