### ISSUE TITLE
4.2. Records for a single species: record count appearing in UI

### ISSUE THREAD

**Issue by charlesroper** [jdrever/ShropBotSoc#96]
Record count is appearing in the UI. Is this supposed to be here? It is not in the wireframes.

![image](https://user-images.githubusercontent.com/176/115091215-db262200-9f0e-11eb-84ea-7e266f2de543.png)

**Comment by jdrever** [comment]
Suggest we keep for now, as useful given we don't get proper paging results from NBN.

**Comment by jdrever** [comment]
As discussed, not in the specs, but until we get pagination working correctly I think it serves a purpose, both for development & user testing.  May be useful beyond that.

From: Charles Roper ***@***.***>
Sent: 17 April 2021 00:03
To: jdrever/ShropBotSoc ***@***.***>
Cc: James Drever ***@***.***>; Assign ***@***.***>
Subject: [jdrever/ShropBotSoc] 4.2. Records for a single species: record count appearing in UI (#96)


Record count is appearing in the UI. Is this supposed to be here? It is not in the wireframes.

[image]<https://user-images.githubusercontent.com/176/115091215-db262200-9f0e-11eb-84ea-7e266f2de543.png>
